export const GET_ERRORS = "GET_ERRORS";
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const ADD_CODEPOINT = "ADD_CODEPOINT";
export const GET_USER = "GET_USER";
export const CHANGE_USER_INFO = "CHANGE_USER_INFO";
export const SET_UNDEFINED_NEXT_MINITASK = "SET_UNDEFINED_NEXT_MINITASK";

export const CHANGE_LOADING = "CHANGE_LOADING";
