root: true
env:
  es6: true
  node: true
  mocha: true
extends: 'eslint:recommended'
rules:
  indent:
    - error
    - 2
    - VariableDeclarator:
        var: 2
        let: 2
        const: 3
      SwitchCase: 1

  brace-style:
    - error
    - stroustrup
  no-lonely-if:
    - error
  no-else-return:
    - error
  linebreak-style:
    - error
    - unix

  keyword-spacing:
    - error
    - before: true
      after: true
  space-before-blocks:
    - error
    - always
  space-before-function-paren:
    - error
    - anonymous: never
      named: never
  func-call-spacing:
    - error
    - never
  space-in-parens:
    - error
    - never
  arrow-spacing:
    - error
    - before: true
      after: true
  block-spacing:
    - error
    - always
  array-bracket-spacing:
    - error
    - never
  object-curly-spacing:
    - error
    - never
  semi-spacing:
    - error
    - before: false
      after: true
  template-curly-spacing:
    - error
    - never

  no-multi-spaces:
    - error
  no-trailing-spaces:
    - error
  eol-last:
    - error
    - always

  semi:
    - error
    - always

  quotes:
    - off
  no-console:
    - off
  no-unused-vars:
    - error
    - args: none
  no-useless-escape:
    - off
  no-regex-spaces:
    - off
