// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag at
// 2019-11-16 16:57:35.254205 +0700 +07 m=+0.113741213

package docs

import (
	"bytes"
	"encoding/json"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "This is a server Api Hocode.",
        "title": "Hocode API",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "1.0"
    },
    "host": "hocodevn.com",
    "basePath": "/api/v1",
    "paths": {
        "/auth/updateusercourse": {
            "post": {
                "description": "UpdateUserCourse",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "UserCourse"
                ],
                "summary": "UpdateUserCourse",
                "parameters": [
                    {
                        "description": "UpdateUserCourse",
                        "name": "course",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/model.BodyUC"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/model.UserCourseOut"
                        }
                    }
                }
            }
        },
        "/auth/usercourse": {
            "get": {
                "description": "get GetUserCourse",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "UserCourse"
                ],
                "summary": "List GetUserCourse",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/model.UserCourse"
                        }
                    }
                }
            }
        },
        "/books": {
            "get": {
                "description": "get books \u003ca href=\"/api/v1/books?page=1\u0026limit=5\"\u003e/api/v1/books?page=1\u0026limit=5\u003c/a\u003e",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Books"
                ],
                "summary": "List Books",
                "operationId": "book_list",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.Book"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Create Book",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Books"
                ],
                "summary": "Create Book",
                "operationId": "book_create",
                "parameters": [
                    {
                        "description": "Create Book",
                        "name": "course",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/model.Book"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/model.Book"
                        }
                    }
                }
            }
        },
        "/books/": {
            "get": {
                "description": "get books \u003ca href=\"/api/v1/books?page=1\u0026limit=5\"\u003e/api/v1/books?page=1\u0026limit=5\u003c/a\u003e",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Books"
                ],
                "summary": "One Books",
                "operationId": "book_one",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/model.Book"
                        }
                    }
                }
            },
            "put": {
                "description": "Update Book",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Books"
                ],
                "summary": "UpdateBooks Book",
                "operationId": "book_update",
                "parameters": [
                    {
                        "description": "Update Book",
                        "name": "course",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/model.Book"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/model.Book"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete Book",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Books"
                ],
                "summary": "Delete Book",
                "operationId": "book_delete",
                "parameters": [
                    {
                        "description": "Delete Book",
                        "name": "course",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/model.Book"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/model.Book"
                        }
                    }
                }
            }
        },
        "/courses": {
            "get": {
                "description": "get courses \u003ca href=\"/api/v1/courses?page=1\u0026limit=5\"\u003e/api/v1/courses?page=1\u0026limit=5\u003c/a\u003e",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Courses"
                ],
                "summary": "List Courses",
                "operationId": "coursesx_list",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.Course"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Create Course",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Courses"
                ],
                "summary": "Create Course",
                "operationId": "coursesx_create",
                "parameters": [
                    {
                        "description": "Create Course",
                        "name": "course",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/model.Course"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/model.Course"
                        }
                    }
                }
            }
        },
        "/courses/": {
            "get": {
                "description": "get courses \u003ca href=\"/api/v1/courses?page=1\u0026limit=5\"\u003e/api/v1/courses?page=1\u0026limit=5\u003c/a\u003e",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Courses"
                ],
                "summary": "One Courses",
                "operationId": "coursesx_one",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/model.Course"
                        }
                    }
                }
            },
            "put": {
                "description": "Update Course",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Courses"
                ],
                "summary": "UpdateCourses Course",
                "operationId": "coursesx_update",
                "parameters": [
                    {
                        "description": "Update Course",
                        "name": "course",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/model.Course"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/model.Course"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete Course",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Courses"
                ],
                "summary": "Delete Course",
                "operationId": "coursesx_delete",
                "parameters": [
                    {
                        "description": "Delete Course",
                        "name": "course",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/model.Course"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/model.Course"
                        }
                    }
                }
            }
        },
        "/courses/{id}": {
            "get": {
                "description": "get courses by ID \u003ca href=\"/courses/5d86e07bfe6e2b157bd3b259\"\u003e/courses/5d86e07bfe6e2b157bd3b259\u003c/a\u003e",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Courses"
                ],
                "summary": "Get Course By ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Course ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/model.Course"
                        }
                    }
                }
            }
        },
        "/courses/{id}/tasks": {
            "get": {
                "description": "Get Task By Courses ID \u003ca href=\"/api/v1/courses/5d86e07bfe6e2b157bd3b259/tasks\"\u003e/api/v1/courses/5d86e07bfe6e2b157bd3b259/tasks\u003c/a\u003e",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Courses"
                ],
                "summary": "Get Task By Courses ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Course ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.Task"
                            }
                        }
                    }
                }
            }
        },
        "/createbook": {
            "post": {
                "description": "Create Book",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Books"
                ],
                "summary": "Create Book",
                "parameters": [
                    {
                        "description": "Create Book",
                        "name": "course",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/model.Book"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/model.Book"
                        }
                    }
                }
            }
        },
        "/events": {
            "get": {
                "description": "get events \u003ca href=\"/api/v1/events?page=1\u0026limit=5\"\u003e/api/v1/events?page=1\u0026limit=5\u003c/a\u003e",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Events"
                ],
                "summary": "List Events",
                "operationId": "event_list",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.Event"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Create Event",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Events"
                ],
                "summary": "Create Event",
                "operationId": "event_create",
                "parameters": [
                    {
                        "description": "Create Event",
                        "name": "course",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/model.Event"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/model.Event"
                        }
                    }
                }
            }
        },
        "/events/": {
            "get": {
                "description": "get events \u003ca href=\"/api/v1/events?page=1\u0026limit=5\"\u003e/api/v1/events?page=1\u0026limit=5\u003c/a\u003e",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Events"
                ],
                "summary": "One Events",
                "operationId": "event_one",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/model.Event"
                        }
                    }
                }
            },
            "put": {
                "description": "Update Event",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Events"
                ],
                "summary": "UpdateEvents Event",
                "operationId": "event_update",
                "parameters": [
                    {
                        "description": "Update Event",
                        "name": "course",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/model.Event"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/model.Event"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete Event",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Events"
                ],
                "summary": "Delete Event",
                "operationId": "event_delete",
                "parameters": [
                    {
                        "description": "Delete Event",
                        "name": "course",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/model.Event"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/model.Event"
                        }
                    }
                }
            }
        },
        "/health_check": {
            "get": {
                "description": "Health Check Server",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Health Check Server",
                "responses": {
                    "200": {
                        "description": "Server Ok",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/minitasks": {
            "get": {
                "description": "get minitasks \u003ca href=\"/api/v1/minitasks?page=1\u0026limit=5\"\u003e/api/v1/minitasks?page=1\u0026limit=5\u003c/a\u003e",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "MiniTasks"
                ],
                "summary": "List MiniTasks",
                "operationId": "minitask_list",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.MiniTask"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Create MiniTask",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "MiniTasks"
                ],
                "summary": "Create MiniTask",
                "operationId": "minitask_create",
                "parameters": [
                    {
                        "description": "Create MiniTask",
                        "name": "minitask",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/model.MiniTask"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/model.MiniTask"
                        }
                    }
                }
            }
        },
        "/minitasks/": {
            "get": {
                "description": "get minitasks \u003ca href=\"/api/v1/minitasks?page=1\u0026limit=5\"\u003e/api/v1/minitasks?page=1\u0026limit=5\u003c/a\u003e",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "MiniTasks"
                ],
                "summary": "One MiniTasks",
                "operationId": "minitask_one",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/model.MiniTask"
                        }
                    }
                }
            },
            "put": {
                "description": "Update MiniTask",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "MiniTasks"
                ],
                "summary": "UpdateMiniTasks MiniTask",
                "operationId": "minitask_update",
                "parameters": [
                    {
                        "description": "Update MiniTask",
                        "name": "minitask",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/model.MiniTask"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/model.MiniTask"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete MiniTask",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "MiniTasks"
                ],
                "summary": "Delete MiniTask",
                "operationId": "minitask_delete",
                "parameters": [
                    {
                        "description": "Delete MiniTask",
                        "name": "minitask",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/model.MiniTask"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/model.MiniTask"
                        }
                    }
                }
            }
        },
        "/minitasks/{id}": {
            "get": {
                "description": "get Minitasks by ID \u003ca href=\"/api/v1/minitasks/5d995ae8fe6e2b0ca40b22fe\"\u003e/api/v1/minitasks/5d995ae8fe6e2b0ca40b22fe\u003c/a\u003e",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Minitasks"
                ],
                "summary": "Get Minitasks By ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Minitask ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/model.MiniTask"
                        }
                    }
                }
            }
        },
        "/tasks": {
            "get": {
                "description": "get tasks \u003ca href=\"/api/v1/tasks?page=1\u0026limit=5\"\u003e/api/v1/tasks?page=1\u0026limit=5\u003c/a\u003e",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tasks"
                ],
                "summary": "List Tasks",
                "operationId": "tasks_list",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.Task"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Create Task",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tasks"
                ],
                "summary": "Create Task",
                "operationId": "tasks_create",
                "parameters": [
                    {
                        "description": "Create Task",
                        "name": "task",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/model.Task"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/model.Task"
                        }
                    }
                }
            }
        },
        "/tasks/": {
            "get": {
                "description": "get tasks \u003ca href=\"/api/v1/tasks?page=1\u0026limit=5\"\u003e/api/v1/tasks?page=1\u0026limit=5\u003c/a\u003e",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tasks"
                ],
                "summary": "One Tasks",
                "operationId": "tasks_one",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/model.Task"
                        }
                    }
                }
            },
            "put": {
                "description": "Update Task",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tasks"
                ],
                "summary": "UpdateTasks Task",
                "operationId": "tasks_update",
                "parameters": [
                    {
                        "description": "Update Task",
                        "name": "task",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/model.Task"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/model.Task"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete Task",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tasks"
                ],
                "summary": "Delete Task",
                "operationId": "tasks_delete",
                "parameters": [
                    {
                        "description": "Delete Task",
                        "name": "task",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/model.Task"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/model.Task"
                        }
                    }
                }
            }
        },
        "/tasks/{id}": {
            "get": {
                "description": "get task by ID \u003ca href=\"/api/v1/tasks/5d86f268fe6e2b31c0673b02\"\u003e/api/v1/tasks/5d86f268fe6e2b31c0673b02\u003c/a\u003e",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tasks"
                ],
                "summary": "Get Task By ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Task ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/model.Task"
                        }
                    }
                }
            }
        },
        "/users": {
            "get": {
                "description": "get users",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "List users",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.User"
                            }
                        }
                    }
                }
            }
        },
        "/users/{id}": {
            "post": {
                "description": "update accounts by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Update user",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Account ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Update account",
                        "name": "account",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/model.User"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/model.User"
                        }
                    }
                }
            },
            "delete": {
                "description": "delete accounts by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Delete user",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Account ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Ok",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "model.BodyUC": {
            "type": "object",
            "properties": {
                "course_id": {
                    "type": "string"
                },
                "minitask_id": {
                    "type": "string"
                },
                "task_id": {
                    "type": "string"
                }
            }
        },
        "model.Book": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "del": {
                    "type": "boolean"
                },
                "id": {
                    "type": "string"
                },
                "image": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "model.Course": {
            "type": "object",
            "properties": {
                "background_image": {
                    "type": "string"
                },
                "course_name": {
                    "type": "string"
                },
                "del": {
                    "type": "boolean"
                },
                "id": {
                    "type": "string"
                },
                "task_solved": {
                    "description": "Name            string     json:\"name\" bson:\"name\"",
                    "type": "object",
                    "$ref": "#/definitions/model.TaskSolved"
                },
                "tasks": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Task"
                    }
                },
                "timestamp": {
                    "type": "string"
                }
            }
        },
        "model.CourseInfo": {
            "type": "object",
            "properties": {
                "background_image": {
                    "type": "string"
                },
                "completed_tasks_count": {
                    "type": "integer"
                },
                "course_id": {
                    "type": "string"
                },
                "course_name": {
                    "type": "string"
                },
                "pass_course": {
                    "type": "boolean"
                },
                "todo_tasks_count": {
                    "type": "integer"
                },
                "total_tasks_count": {
                    "type": "integer"
                }
            }
        },
        "model.Event": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "del": {
                    "type": "boolean"
                },
                "id": {
                    "type": "string"
                },
                "image": {
                    "type": "string"
                },
                "link": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "model.Input": {
            "type": "object",
            "properties": {
                "type": {
                    "type": "string"
                },
                "value": {
                    "type": "string"
                }
            }
        },
        "model.MiniTask": {
            "type": "object",
            "properties": {
                "avatar": {
                    "type": "string"
                },
                "code_point": {
                    "type": "integer"
                },
                "del": {
                    "type": "boolean"
                },
                "id": {
                    "type": "string"
                },
                "level": {
                    "type": "string"
                },
                "mini_task_desc": {
                    "type": "string"
                },
                "mini_task_name": {
                    "type": "string"
                },
                "name_func": {
                    "type": "string"
                },
                "output_type_func": {
                    "type": "string"
                },
                "point_unlock": {
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                },
                "task_id": {
                    "type": "string"
                },
                "template_code": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "string"
                },
                "unit_tests": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.UnitTest"
                    }
                },
                "vitri": {
                    "type": "boolean"
                }
            }
        },
        "model.MiniTaskInfo": {
            "type": "object",
            "properties": {
                "minitask_id": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "model.Task": {
            "type": "object",
            "properties": {
                "background_image": {
                    "type": "string"
                },
                "course_id": {
                    "type": "string"
                },
                "del": {
                    "type": "boolean"
                },
                "id": {
                    "type": "string"
                },
                "minitasks": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.MiniTask"
                    }
                },
                "task_name": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "string"
                }
            }
        },
        "model.TaskSolved": {
            "type": "object",
            "properties": {
                "task_count": {
                    "description": "ID            bson.ObjectId json:\"id\" bson:\"_id,omitempty\"",
                    "type": "integer"
                },
                "tasks_complete": {
                    "type": "integer"
                },
                "timestamp": {
                    "type": "string"
                }
            }
        },
        "model.UnitTest": {
            "type": "object",
            "properties": {
                "expected_output": {
                    "type": "string"
                },
                "inputs": {
                    "description": "ID             bson.ObjectId json:\"id\" bson:\"_id,omitempty\"",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Input"
                    }
                }
            }
        },
        "model.User": {
            "type": "object",
            "properties": {
                "avatar": {
                    "type": "string"
                },
                "codepoint": {
                    "type": "integer"
                },
                "del": {
                    "type": "boolean"
                },
                "email": {
                    "type": "string"
                },
                "firstname": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "lastname": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "timestamp": {
                    "description": "Company []company      json:\"company,omitempty\" bson:\"company,omitempty\"",
                    "type": "string"
                },
                "token": {
                    "type": "string"
                }
            }
        },
        "model.UserCourse": {
            "type": "object",
            "properties": {
                "course_info": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.CourseInfo"
                    }
                },
                "del": {
                    "type": "boolean"
                },
                "id": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "model.UserCourseOut": {
            "type": "object",
            "properties": {
                "codepoint": {
                    "type": "integer"
                },
                "next_minitask": {
                    "type": "object",
                    "$ref": "#/definitions/model.MiniTask"
                },
                "user_course": {
                    "type": "object",
                    "$ref": "#/definitions/model.UserCourse"
                },
                "user_minitask": {
                    "type": "object",
                    "$ref": "#/definitions/model.UserMiniTask"
                }
            }
        },
        "model.UserMiniTask": {
            "type": "object",
            "properties": {
                "course_info": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.MiniTaskInfo"
                    }
                },
                "del": {
                    "type": "boolean"
                },
                "id": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{ Schemes: []string{}}

type s struct{}

func (s *s) ReadDoc() string {
	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface {}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, SwaggerInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
